spring:
  servlet:
    multipart:
      max-file-size: 20000MB
      max-request-size: 20000MB

file-service:
  rootFilePath: ${ROOT_FILE_PATH}

security:
  oauth2:
    resource:
      userInfoUri: ${AUTH_SERVICE_URI}/oauth/current